# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
version: "3"

services: 
  valheim: 
    build: 
      context: .
    cap_add:
      - sys_nice
    volumes: 
      - aws:/home/valheim/.aws/
      - config:/config
      - valheim:/opt/valheim
      - ./worlds_local:/home/valheim/.config/unity3d/IronGate/Valheim/worlds_local
    ports: 
      - "2456-2458:2456-2458/udp"
    environment:
      - SERVER_PORT=2456
    env_file:
      - .env
    restart: always
    stop_grace_period: 2m
volumes:
  config:
  valheim:
  aws: